### ISSUE TITLE
VURDER og eventuelt implementer kontrakttest for fdk-fuseki-service

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-fuseki-service#7]
NB! VURDER OM DENNE TJENESTEN TRENGER DENNE TESTEN.
***********
Ta utgangspunkt i
a-frontend-service
a-backend-service

og verifiser at de ulike tjenestene har en specc fil.
Deretter skal vi skrive kontrakttester/featuretester for den enkelte tjenesten.

Implementere kontrakttest/featurestest for tjenesten:
fdk-fuseki-service

**Comment by stigbd** [comment]
Lukker, da tjenesten er tatt ned.
